kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nginx.fullname" . }}-conf
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- (.Files.Get "nginx.conf") | nindent 4 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nginx.fullname" . }}-confd
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  {{- $currentScope := . -}}
  {{ range $path, $_ :=  .Files.Glob "conf.d/**.conf" }}
    {{- with $currentScope}}
  {{ $path | base }}: |
    {{- tpl (.Files.Get $path) . | nindent 4 -}}
    {{- end }}
  {{- end }}
