language: go

go:
  - 1.13.5

before_install:
  - go get -v golang.org/x/lint/golint
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/kisielk/errcheck

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - go vet -shift=false .
  - $GOPATH/bin/golint ./...
  #- $GOPATH/bin/errcheck ./...
  - go test -cpu=2 -race -v ./...
  - go test -cpu=2 -covermode=atomic ./...
