# install istio individually, since the validation won't pass
istio:
  enabled: false

cert-manager:
  enabled: false

mariadb:
  architecture: standalone
  auth:
    ## @required
    ##
    rootPassword: ""
    database: bitnami_ghost

  ## @optional
  ##
  initdbScriptsConfigMap: ""

apps:
  nfs:
    ## @required
    ##
    server: ""
    path: /
  ghost:
    ghostUsername: kennylong
    ## @required
    ##
    ghostPassword: ""
    ## @required
    ##
    ghostEmail: ""
    ghostBlogTitle: Kennylong's Blog
    ghostHost: kennylong.io
    ghostSkipInstall: true
    ghostEnableHttps: true

    persistence:
      ## @required
      ##
      existingClaim: apps-storage
    volumePermissions:
      enabled: true

    externalDatabase:
      ## @required
      ##
      host: apps-mariadb
      port: 3306
      user: root
      ## @required
      ##
      password: ""
      database: bitnami_ghost
  
  www:
    github:
      ## @optional
      ##
      token: ""

    ga: UA-63860199-1
    origin: https://www.xiaolongtongxue.com
  
  shadowsocks-rust:
    image:
      repository: teddysun/shadowsocks-rust
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "debian-1.9.0"

    servers:
    - name: default
      server: 0.0.0.0
      server_port: 80
      ## @required
      ##
      password: ""
      method: chacha20-ietf-poly1305
      fast_open: true
      mode: tcp_and_udp
      plugin: obfs-server
      plugin_opts: obfs=http

  omnifocus:
    ## @required
    ##
    username: ""
    ## @required
    ##
    password: ""