port: 1217
repo_dir: /repo
glob_docs:
  - README.*
skip_dirs:
  - .*
  - assets
github:
  user: longkai
  repo: essays
  hook_secret: yuejia
  access_token: c0d2fbcbdc9660dcdc819300aa940c2f8a558d00
medium_token: 2a36d936304fc8cd2836d3bf6c6fff830dc24180b066c3c28357eac25f8260947
meta:
  ga: UA-63860199-1
  gf: false
  origin: https://xiaolongtongxue.com # required only if using meidum
  bio: |
    Gopher;
    C/Unix Programmer;
    macOS/iOS Developer;
    Java/Android Engineer;
  link: /
  name: 小龙同学
  title: 小龙同学
  mail: i@xiaolongtongxue.com
  github: https://github.com/longkai
  medium: https://essays.xiaolongtongxue.com
  twitter: https://twitter.com/xiaolongtongxue
  instagram: https://www.instagram.com/0xcaffee
  stackoverflow: https://stackoverflow.com/users/3280791/longkai
redir: # Redirection mapping
  "/a": "/apps/pixiu"
