apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: websocket-ss
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  hosts:
  - "live.xiaolongtongxue.com"
  - "stream.kennylong.io"
  gateways:
  - {{ include "istio.fullname" . }}-gateway
  http:
  - name: websocket
    match:
    - uri:
        exact: /stream
      headers:
        connection:
          exact: Upgrade
    - uri:
        exact: /
      headers:
        connection:
          exact: Upgrade
    route:
    - destination:
        host: apps-shadowsocks-rust.kennylong.svc.cluster.local
  - name: default
    redirect:
      authority: www.xiaolongtongxue.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: essays
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  hosts:
  - "xiaolongtongxue.com"
  - "www.xiaolongtongxue.com"
  gateways:
  - {{ include "istio.fullname" . }}-gateway
  http:
  - match:
    - authority:
        exact:
          xiaolongtongxue.com
    redirect:
      authority: www.xiaolongtongxue.com
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: apps-nginx.kennylong.svc.cluster.local
      headers:
        response:
          set:
            strict-transport-security: max-age=63072000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dl
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  hosts:
  - "dl.xiaolongtongxue.com"
  - "dl.kennylong.io"
  gateways:
  - {{ include "istio.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: apps-nginx.kennylong.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: omnifocus
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  hosts:
  - "omnifocus.xiaolongtongxue.com"
  - "omnifocus.kennylong.io"
  gateways:
  - {{ include "istio.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: apps-omnifocus.kennylong.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ghost
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  hosts:
  - "kennylong.io"
  - "www.kennylong.io"
  gateways:
  - {{ include "istio.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 443
        host: apps-ghost.kennylong.svc.cluster.local
      headers:
        response:
          set:
            strict-transport-security: max-age=63072000
---
# this only a local test...
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  labels:
    {{- include "istio.labels" . | nindent 4 }}
spec:
  hosts:
  - "dev.kennylong.io"
  gateways:
  - {{ include "istio.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: httpbin.default.svc.cluster.local
---