apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storage
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: {{ .Release.Name }}-storage
  resources:
    requests:
      storage: 50Gi

{{ if .Values.nfs -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-storage
  labels:
    {{- include "apps.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
{{- end -}}